### ISSUE TITLE
`history.replaceState` infinite loop

### ISSUE THREAD

**Issue by bredfield** [userflow/userflow.js#10]
We've run into the following issue multiple times with a specific user:

`SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds`

Some detail:
```{message: "Attempt to use history.replaceState() more than 100 times per 30 seconds"…}
message: "Attempt to use history.replaceState() more than 100 times per 30 seconds"
name: "SecurityError"
stack: "replaceState@[native code]
@https://js.userflow.com/es2020/userflow.js:1:10230
@https://cdn.lr-ingest.com/logger-1.min.js:1:230997
...
line: 1
column: 10230
sourceURL: "https://js.userflow.com/es2020/userflow.js"
```

This was encountered on Safari v. 16.5.1.

I'm unable to recreate myself -- any insight would be much appreciated!

**Comment by sebastianseilund** [comment]
Hi @bredfield . Closing here since we didn't hear back from you. Feel free to write us again here or at support@userflow.com if this is still an issue :)
