### ISSUE TITLE
Cannot read properties of undefined (reading 'isExpensive')

### ISSUE THREAD

**Issue by giangle-datadive** [userflow/userflow.js#11]
We always got this error when page is loaded

`Cannot read properties of undefined (reading 'isExpensive')`

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isExpensive')
    at flow-condition-types.b491ab7a.js:1:29621
    at Array.map (<anonymous>)
    at Object.track (flow-condition-types.b491ab7a.js:1:29550)
    at Pt.addTracker (userflow.js:1:60656)
```

<img width="445" alt="image" src="https://github.com/userflow/userflow.js/assets/22128074/ad0d546b-a030-4b65-b367-ae6cff97d0fe">

Could you guys please check it?

**Comment by sebastianseilund** [comment]
Hi there,

How did you install Userflow.js? If you're running on the newest version (from our CDN, or via userflow.js-self-hosted), then this should not be possible.

Is there a way I can reproduce this in your app in my own browser? You can send login details to support@userflow.com

Thanks!

**Comment by giangle-datadive** [comment]
I installed it via npm, Sorry I cannot share the login details because our app is authenticated with google SSO (let me ask my manager first).  The error started to appear around 09/13 did you guys return a new version on that day?
```json
"userflow.js": "^2.7.0",
```

**Comment by sebastianseilund** [comment]
I don't see anything related to this.

I need to look at your specific account to figure out what's going on here. Can you please reach out to us at support@userflow.com so we can share some details not suitable for GitHub? :)

I'll close here.

**Comment by abrantes01** [comment]
Hey @sebastianseilund, did you managed to resolve this issue? I've exactly the same error with my Userflow setup

**Comment by sebastianseilund** [comment]
We need to dive into what exactly is happening with your account in this case. Can you please reach out to us at [support@userflow.com](mailto:support@userflow.com) so we can share some details not suitable for GitHub? :)
