### ISSUE TITLE
logging "Could not load Userflow.js" on failure of script loading

### ISSUE THREAD

**Issue by mesfahanisimscale** [userflow/userflow.js#12]
When the remove script of useflow fails to load, an error is [logged](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L244) using `console.error` in addition to the fact that the promise is [rejected](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L245). This results in multiple errors being reported in different ways, which clutters the error reporting. Can you please demote the severity of the logging to `console.warn`? The promise rejection already ends up in console as an error, and can be caught by the caller of `userflow.load` and handled appropriately.

**Comment by vigbeamer** [comment]
We've made the necessary adjustments to demote the severity of the logging to `console.warn` in our new version [Userflow@2.12.1.](https://www.npmjs.com/package/userflow.js)

Thank you for your feedback!
