### ISSUE TITLE
`Page Viewed` is not being tracked when using @tanstack/router

### ISSUE THREAD

**Issue by truongtrongtin** [userflow/userflow.js#13]
We migrate the app from using `react-router-dom`(works fine) to `@tanstack/router`. But the `Page Viewed` of user session is not tracked when navigating between routes,  may be because the `UpdateClientContext` event  is not fired.

**Comment by vigbeamer** [comment]
@truongtrongtin, This appears to be due to @tanstack/router patching the pushState method, which might be preventing the `UpdateClientContext` event from firing.

We are currently investigating this issue to identify a solution. We appreciate your patience and will keep you updated on our progress.

**Comment by vigbeamer** [comment]
We have addressed the issue you raised and released a new version of the package, [Userflow@2.12.1.](https://www.npmjs.com/package/userflow.js)

Please upgrade to the latest version and let us know if you encounter any further issues.

Thank you for your feedback!
