### ISSUE TITLE
Uncaught exceptions at init time when script fails to load

### ISSUE THREAD

**Issue by dubzzz** [userflow/userflow.js#19]
During its initialization cycle the package may trigger some unwanting "unhandled promise rejections" when attempting to call `stubVoid` and related.

It happens that while the code logs a warning in such case ([here](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L277)), it also forwards the error within a rejected Promise ([here](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L278)). Unfortunately this Promise is not caught in some code paths making it being considered as an uncaught exception.

The code [here](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L299) should probably be adapted as follow:

```js
  var stubVoid = function (
    // eslint-disable-next-line es5/no-rest-parameters
    method: ConditionalKeys<Userflow, (...args: any[]) => void>
  ) {
    userflow![method] = function () {
      var args = Array.prototype.slice.call(arguments)
      userflow!.load().then(() => {}, () => {})
      q.push([method, null, args])
    } as any
  }
```

_I just added the `.then(() => {}, () => {})` which mostly catch the Promise if it fails_

And the code [here](https://github.com/userflow/userflow.js/blob/main/src/userflow.ts#L311):

```js
  var stubPromise = function (
    // eslint-disable-next-line es5/no-rest-parameters
    method: ConditionalKeys<Userflow, (...args: any[]) => Promise<void>>
  ) {
    userflow![method] = function () {
      var args = Array.prototype.slice.call(arguments)
      userflow!.load().then(() => {}, () => {})
      var deferred: Deferred
      var promise = new Promise<void>(function (resolve, reject) {
        deferred = {resolve: resolve, reject: reject}
      })
      q.push([method, deferred!, args])
      return promise
    } as any
  }
```

_I just added the `.then(() => {}, () => {})` which mostly catch the Promise if it fails_

Why the issue? Tools such as Datadog or Sentry reports such uncaught and it tends to make monitoring a bit blurry.

**Comment by scottyg** [comment]
@dubzzz So, I just encountered this issue in a nextjs app. After adding [these](https://docs.userflow.com/docs/dev/csp) to our content security policy. It seems to be working.

**Comment by JayaKrishnaNamburu** [comment]
> @dubzzz So, I just encountered this issue in a nextjs app. After adding [these](https://docs.userflow.com/docs/dev/csp) to our content security policy. It seems to be working.

This is what the script is aiming for. To let the reporting tools know that loading `userflow` is failing. And can be quickly looked into. If these exceptions are handled, then the reporting tools will ignore them.

**Comment by dubzzz** [comment]
> This is what the script is aiming for. To let the reporting tools know that loading userflow is failing.

I'm totally ok with userflow failing to load. Actually I expect some users to use things such as UBlock or other tracking blocker. As such this log is spamming our monitoring without any way to avoid it (no way to catch it).

**Comment by dubzzz** [comment]
The "without any way to avoid it" is a huge problem IMO. It makes bill of solutions such as Sentry or Datadog go higher because of a log we cannot block or control on our end.

**Comment by JayaKrishnaNamburu** [comment]
> The "without any way to avoid it" is a huge problem IMO.

totally agree with that, will get back with some options 👍
