### ISSUE TITLE
The flow is just being closed automatically

### ISSUE THREAD

**Issue by xurshid29** [userflow/userflow.js#5]
Hello, I’m facing some strange problem with userflow. The flow is just being closed automatically, anytime it wants. Every time differently, sometimes it works till the end just fine, sometime just disappeared. Below are 3 screenrecords, which show the 2 occurrences of that problem and 1 normal one;

Userflow.js version is 2.4.0

Initialization:
```
    userflow.init("ct_***");

    ...

    if (!userflow.isIdentified()) {
        console.log("rendered isIdentified");
        void userflow.identify(profile.user.id);
        userflow.setResourceCenterLauncherHidden(true);
    }
    ...
```

https://user-images.githubusercontent.com/5887811/162435892-9d1ff016-2a0a-41ae-8eae-ddcc522ae12d.mov

https://user-images.githubusercontent.com/5887811/162435911-ec371b19-52c1-4c53-9562-5e1fc66831ee.mov

https://user-images.githubusercontent.com/5887811/162435937-9ca0ef71-d7ee-452a-8a73-a260ff612316.mov

**Comment by sebastianseilund** [comment]
Hello there :). Did you figure this out?

**Comment by xurshid29** [comment]
Yeap) It was a silly situation :) 
It was due to another person with same profile who had been logged in to another our project with different subdomain. My preview request was shown to him also and he was closing it. 
I was sure that preview will be checked by the URL which I've set, but it was exposed to other subdomains also where with users with same id
