### ISSUE TITLE
Userflow.js socket error

### ISSUE THREAD

**Issue by wallies** [userflow/userflow.js#6]
We are seeing a lot of these errors. Do they have meaning or should we just ignore them? We are using userflow 2.3.0

```
Userflow.js socket error {"isTrusted":true}
```

**Comment by sebastianseilund** [comment]
This is usually due to a network error (between your user's computer and our back-end). It can happen when Userflow.js is running across many user on many different devices and networks of different qualities. I'd only be worried if it happens consistently and across a large number of users.
