### ISSUE TITLE
Unable to use bfcache due to userflow script using unload event

### ISSUE THREAD

**Issue by NishuGoel** [userflow/userflow.js#8]
The[ userflow script](https://js.userflow.com/es2020/userflow.js) triggers an "unload" event which is [not recommended by Chrome](https://web.dev/bfcache/#never-use-the-unload-event). This currently limits us to use Back-forward cache on our application.

Use the `pagehide` event instead of `unload`. A quick fix will be very appreciated.  [Read more here](https://web.dev/bfcache/)

<img width="742" alt="Screenshot 2023-04-10 at 18 00 52" src="https://user-images.githubusercontent.com/26349046/230941360-a8c4bf6a-b746-4cd9-a8f7-42485c5111df.png">

**Comment by sebastianseilund** [comment]
Hi! Thanks for reporting this. We agree that using `pagehide` would be better. Give us a few days to deploy a fix :)

**Comment by sebastianseilund** [comment]
@NishuGoel This has been fixed now. `pagehide` was a pure drop-in replacement for `unload`. Thanks again for helping us improve Userflow.js :)

**Comment by NishuGoel** [comment]
I see, but the latest version is 2.7.0, which adds [this script ](https://js.userflow.com/es2020/userflow.js) which still seems to have the unload event.

**Comment by sebastianseilund** [comment]
You're right. Thanks. That's from a dependency we use. I can see that they've also switched to `pagehide` in a recent version. Will try to upgrade.

**Comment by sebastianseilund** [comment]
Done. No `unload` should be left now :)

**Comment by NishuGoel** [comment]
Charm! Thank you 👏
