### ISSUE TITLE
Horizontal scroll bar issue

### ISSUE THREAD

**Issue by agnostic-coder** [userflow/userflow.js#9]
I noticed that the help button contains a horizontal scroll bars, suspected that is was messed by some global styling but after checking your website I noticed you have this issue as well ( see the attached images)

On windows:

![image](https://github.com/userflow/userflow.js/assets/134928294/e18a406c-7402-4a66-ac49-20a5cf844bbe)

On Mac:
![image](https://github.com/userflow/userflow.js/assets/134928294/b6223a22-192a-4059-a4a0-6be57c6041f0)

Thanks for taking a look at this.

**Comment by agnostic-coder** [comment]
temporary fox for now. 

```ts
setTimeout(() => {
    const userFlowFrame = document.querySelector(
      'iframe.userflowjs-resource-center-frame'
    ) as HTMLIFrameElement;
    if (!userFlowFrame) return;
    const resourceDiv = userFlowFrame.contentWindow.document.querySelector(
      '.userflowjs-resource-center-frame-root--closed'
    ) as HTMLDivElement;
    if (resourceDiv) {
      resourceDiv.style.width = 'unset';
    }
  }, 1000);
```

I had to rely on setTimeout since there is no event that I can use to know that userflow is mounted, it would be a great addition if you can add that to the list of supported event listeners

**Comment by sebastianseilund** [comment]
Hi @agnostic-coder,

Thanks for reporting this! It was a display issue introduced today only visible with the "Show scroll bars: Always" setting.

It has been fixed now. Sorry for the trouble :)
